name: Greeting from Noah
on: push

jobs:
  my-job:
    name: My job
    runs-on: ubuntu-latest
    steps:
    - name: Print a greeting
      env:
        MY_VAR: Hi there! My name is
        FIRST_NAME: Chun
        MIDDLE_NAME: Tung
        LAST_NAME: Chan
      run:
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME
